[2025-05-24T07:30:00.045Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:00.047Z] Process exited with code 1
[2025-05-24T07:30:01.123Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:01.124Z] Process exited with code 1
[2025-05-24T07:30:02.190Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:02.191Z] Process exited with code 1
[2025-05-24T07:30:03.297Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:03.298Z] Process exited with code 1
[2025-05-24T07:30:04.356Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:04.370Z] Process exited with code 1
[2025-05-24T07:30:05.417Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:05.433Z] Process exited with code 1
[2025-05-24T07:30:06.503Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:06.503Z] Process exited with code 1
[2025-05-24T07:30:07.577Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:07.578Z] Process exited with code 1
[2025-05-24T07:30:08.661Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:08.661Z] Process exited with code 1
[2025-05-24T07:30:09.737Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:09.738Z] Process exited with code 1
[2025-05-24T07:30:10.803Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:10.803Z] Process exited with code 1
[2025-05-24T07:30:11.889Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:11.890Z] Process exited with code 1
[2025-05-24T07:30:12.955Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:12.956Z] Process exited with code 1
[2025-05-24T07:30:14.041Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:14.042Z] Process exited with code 1
[2025-05-24T07:30:15.123Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:15.124Z] Process exited with code 1
[2025-05-24T07:30:16.203Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:16.204Z] Process exited with code 1
[2025-05-24T07:30:17.278Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:17.294Z] Process exited with code 1
[2025-05-24T07:30:18.356Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:18.357Z] Process exited with code 1
[2025-05-24T07:30:19.413Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:19.414Z] Process exited with code 1
[2025-05-24T07:30:20.464Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:20.465Z] Process exited with code 1
[2025-05-24T07:30:21.544Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:21.544Z] Process exited with code 1
[2025-05-24T07:30:22.609Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:22.609Z] Process exited with code 1
[2025-05-24T07:30:23.678Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:23.678Z] Process exited with code 1
[2025-05-24T07:30:24.728Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:24.747Z] Process exited with code 1
[2025-05-24T07:30:25.797Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:25.811Z] Process exited with code 1
[2025-05-24T07:30:26.878Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:26.891Z] Process exited with code 1
[2025-05-24T07:30:27.945Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:27.974Z] Process exited with code 1
[2025-05-24T07:30:29.065Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:29.068Z] Process exited with code 1
[2025-05-24T07:30:30.115Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:30.131Z] Process exited with code 1
[2025-05-24T07:30:31.193Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:31.210Z] Process exited with code 1
[2025-05-24T07:30:32.277Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:32.277Z] Process exited with code 1
[2025-05-24T07:30:33.343Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:33.343Z] Process exited with code 1
[2025-05-24T07:30:34.405Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:34.405Z] Process exited with code 1
[2025-05-24T07:30:35.465Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:35.469Z] Process exited with code 1
[2025-05-24T07:30:36.544Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:36.546Z] Process exited with code 1
[2025-05-24T07:30:37.619Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:37.619Z] Process exited with code 1
[2025-05-24T07:30:38.693Z] [STDERR] node:internal/modules/cjs/loader:1404
  throw err;
  ^

Error: Cannot find module 'C:\Users\karti\Multi-Agent Chatbot System\agents\llama3\index.js'
    at Function._resolveFilename (node:internal/modules/cjs/loader:1401:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1057:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1062:22)
    at Function._load (node:internal/modules/cjs/loader:1211:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:235:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:171:5)
    at node:internal/main/run_main_module:36:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

Node.js v22.16.0
[2025-05-24T07:30:38.694Z] Process exited with code 1
[2025-05-24T07:51:46.266Z] [STDOUT] [32minfo[39m: agent-llama3 running on port 3002 {"service":"multi-agent-chat","timestamp":"2025-05-24T07:51:46.265Z"}
[2025-05-24T07:53:47.275Z] [STDOUT] [0mGET /status [32m200[0m 1.325 ms - 66[0m
[2025-05-24T07:57:07.037Z] [STDOUT] [32minfo[39m: Shutting down LLaMA 3 agent... {"service":"multi-agent-chat","timestamp":"2025-05-24T07:57:07.035Z"}
[2025-05-24T07:57:07.047Z] Process exited with code null
[2025-05-24T07:57:40.865Z] [STDOUT] [32minfo[39m: agent-llama3 running on port 3002 {"service":"multi-agent-chat","timestamp":"2025-05-24T07:57:40.864Z"}
[2025-05-24T07:57:54.216Z] [STDOUT] [0mGET /status [32m200[0m 1.222 ms - 66[0m
[2025-05-24T08:01:40.035Z] [STDOUT] [0mGET /status [32m200[0m 0.371 ms - 66[0m
[2025-05-24T08:02:37.205Z] [STDOUT] [32minfo[39m: Shutting down LLaMA 3 agent... {"service":"multi-agent-chat","timestamp":"2025-05-24T08:02:37.203Z"}
[2025-05-24T08:02:37.212Z] Process exited with code null
[2025-05-24T08:04:53.441Z] [STDOUT] [32minfo[39m: agent-llama3 running on port 3002 {"service":"multi-agent-chat","timestamp":"2025-05-24T08:04:53.440Z"}
[2025-05-24T08:04:59.660Z] [STDOUT] [0mGET /status [32m200[0m 1.159 ms - 66[0m
[2025-05-24T08:05:01.587Z] [STDOUT] [0mGET /status [32m200[0m 0.236 ms - 66[0m
[2025-05-24T08:05:38.078Z] [STDOUT] [32minfo[39m: Shutting down LLaMA 3 agent... {"service":"multi-agent-chat","timestamp":"2025-05-24T08:05:38.076Z"}
[2025-05-24T08:05:38.088Z] Process exited with code null
[2025-05-24T08:08:38.846Z] [STDOUT] [32minfo[39m: agent-llama3 running on port 3002 {"service":"multi-agent-chat","timestamp":"2025-05-24T08:08:38.843Z"}
[2025-05-24T08:08:44.926Z] [STDOUT] [0mGET /status [32m200[0m 1.593 ms - 66[0m
[2025-05-24T08:11:00.766Z] [STDOUT] [32minfo[39m: Shutting down LLaMA 3 agent... {"service":"multi-agent-chat","timestamp":"2025-05-24T08:11:00.763Z"}
[2025-05-24T08:11:00.780Z] Process exited with code null
[2025-05-24T08:15:14.773Z] [STDOUT] [32minfo[39m: agent-llama3 running on port 3002 {"service":"multi-agent-chat","timestamp":"2025-05-24T08:15:14.771Z"}
[2025-05-24T08:15:18.401Z] [STDOUT] [0mGET /status [32m200[0m 1.295 ms - 66[0m
[2025-05-24T08:15:37.558Z] [STDOUT] [0mGET /status [32m200[0m 0.455 ms - 66[0m
[2025-05-24T08:17:35.521Z] [STDOUT] [32minfo[39m: Shutting down LLaMA 3 agent... {"service":"multi-agent-chat","timestamp":"2025-05-24T08:17:35.519Z"}
[2025-05-24T08:17:35.535Z] Process exited with code null
[2025-05-24T08:22:56.957Z] [STDOUT] [32minfo[39m: agent-llama3 running on port 3002 {"service":"multi-agent-chat","timestamp":"2025-05-24T08:22:56.956Z"}
[2025-05-24T08:23:02.177Z] [STDOUT] [0mGET /status [32m200[0m 1.680 ms - 66[0m
[2025-05-24T08:24:29.586Z] [STDOUT] [32minfo[39m: agent-llama3 received message {"from":"manager","service":"multi-agent-chat","timestamp":"2025-05-24T08:24:29.584Z"}
[2025-05-24T08:24:29.586Z] [STDOUT] Generating response with model: llama3:latest
[2025-05-24T08:24:45.771Z] [STDOUT] [31merror[39m: Error generating response with llama3:latest: {"service":"multi-agent-chat","timestamp":"2025-05-24T08:24:45.770Z"}
[2025-05-24T08:24:45.771Z] [STDOUT] [31merror[39m: agent-llama3 error: {"service":"multi-agent-chat","timestamp":"2025-05-24T08:24:45.770Z"}
[2025-05-24T08:24:45.772Z] [STDOUT] [0mPOST /message [31m500[0m 16186.979 ms - 160[0m
[2025-05-24T08:25:35.294Z] [STDOUT] [32minfo[39m: Shutting down LLaMA 3 agent... {"service":"multi-agent-chat","timestamp":"2025-05-24T08:25:35.290Z"}
[2025-05-24T08:25:35.307Z] Process exited with code null
[2025-05-25T15:30:00.466Z] [STDOUT] [32minfo[39m: agent-llama3 running on port 3002 {"service":"multi-agent-chat","timestamp":"2025-05-25T15:30:00.464Z"}
[2025-05-25T15:30:29.299Z] [STDOUT] [0mGET /status [32m200[0m 2.601 ms - 66[0m
[2025-05-25T15:30:30.909Z] [STDOUT] [0mGET /status [32m200[0m 0.497 ms - 66[0m
[2025-05-25T15:30:32.205Z] [STDOUT] [0mGET /status [32m200[0m 0.327 ms - 66[0m
[2025-05-25T15:30:33.612Z] [STDOUT] [0mGET /status [32m200[0m 0.469 ms - 66[0m
[2025-05-25T15:31:23.852Z] [STDOUT] [32minfo[39m: agent-llama3 received message {"from":"manager","service":"multi-agent-chat","timestamp":"2025-05-25T15:31:23.851Z"}
[2025-05-25T15:31:23.854Z] [STDOUT] Generating response with model: llama3:latest
[2025-05-25T15:31:47.587Z] [STDOUT] [0mPOST /message [32m200[0m 23734.906 ms - 4280[0m
[2025-05-25T15:33:24.558Z] [STDOUT] [32minfo[39m: agent-llama3 received message {"from":"manager","service":"multi-agent-chat","timestamp":"2025-05-25T15:33:24.558Z"}
[2025-05-25T15:33:24.558Z] [STDOUT] Generating response with model: llama3:latest
[2025-05-25T15:33:41.291Z] [STDOUT] [0mPOST /message [32m200[0m 16732.610 ms - 2696[0m
[2025-05-25T15:53:31.639Z] [STDOUT] [0mGET /status [32m200[0m 0.397 ms - 66[0m
[2025-05-25T16:05:33.022Z] Process exited with code 3221225786
[2025-05-26T05:07:13.806Z] [STDOUT] [32minfo[39m: agent-llama3 running on port 3002 {"service":"multi-agent-chat","timestamp":"2025-05-26T05:07:13.804Z"}
[2025-05-26T05:07:21.454Z] [STDOUT] [0mGET /status [32m200[0m 1.285 ms - 66[0m
[2025-05-26T05:07:22.863Z] [STDOUT] [0mGET /status [32m200[0m 0.396 ms - 66[0m
[2025-05-26T05:07:24.098Z] [STDOUT] [0mGET /status [32m200[0m 0.544 ms - 66[0m
[2025-05-26T05:08:11.763Z] [STDOUT] [32minfo[39m: agent-llama3 received message {"from":"manager","service":"multi-agent-chat","timestamp":"2025-05-26T05:08:11.761Z"}
[2025-05-26T05:08:11.766Z] [STDOUT] Generating response with model: llama3:latest
[2025-05-26T05:08:29.958Z] [STDOUT] [0mPOST /message [32m200[0m 18195.964 ms - 3157[0m
[2025-05-26T05:09:43.045Z] [STDOUT] [32minfo[39m: agent-llama3 received message {"from":"manager","service":"multi-agent-chat","timestamp":"2025-05-26T05:09:43.044Z"}
[2025-05-26T05:09:43.045Z] [STDOUT] Generating response with model: llama3:latest
[2025-05-26T05:09:58.281Z] [STDOUT] [0mPOST /message [32m200[0m 15235.723 ms - 2448[0m
[2025-05-26T05:16:11.002Z] [STDOUT] [0mGET /status [32m200[0m 0.328 ms - 66[0m
[2025-05-26T05:16:20.641Z] [STDOUT] [32minfo[39m: Shutting down LLaMA 3 agent... {"service":"multi-agent-chat","timestamp":"2025-05-26T05:16:20.638Z"}
[2025-05-26T05:16:20.659Z] Process exited with code null
[2025-05-26T05:24:28.697Z] [STDOUT] [32minfo[39m: agent-llama3 running on port 3002 {"service":"multi-agent-chat","timestamp":"2025-05-26T05:24:28.697Z"}
[2025-05-26T05:24:36.541Z] [STDOUT] [0mGET /status [32m200[0m 1.356 ms - 66[0m
[2025-05-26T05:24:37.923Z] [STDOUT] [0mGET /status [32m200[0m 0.229 ms - 66[0m
[2025-05-26T05:26:19.437Z] [STDOUT] [32minfo[39m: agent-llama3 received message {"from":"manager","service":"multi-agent-chat","timestamp":"2025-05-26T05:26:19.437Z"}
[2025-05-26T05:26:19.438Z] [STDOUT] Generating response with model: llama3:latest
[2025-05-26T05:26:38.487Z] [STDOUT] [0mPOST /message [32m200[0m 19049.042 ms - 3285[0m
[2025-05-26T05:29:30.552Z] [STDOUT] [32minfo[39m: agent-llama3 received message {"from":"manager","service":"multi-agent-chat","timestamp":"2025-05-26T05:29:30.552Z"}
[2025-05-26T05:29:30.553Z] [STDOUT] Generating response with model: llama3:latest
[2025-05-26T05:30:00.560Z] [STDERR] Error generating response with model llama3:latest: timeout of 30000ms exceeded
[2025-05-26T05:30:00.561Z] [STDOUT] Retrying... (1 attempts left)
Generating response with model: llama3:latest
[2025-05-26T05:30:30.564Z] [STDERR] Error generating response with model llama3:latest: timeout of 30000ms exceeded
[2025-05-26T05:30:30.564Z] [STDOUT] Retrying... (0 attempts left)
Generating response with model: llama3:latest
[2025-05-26T05:31:00.568Z] [STDERR] Error generating response with model llama3:latest: timeout of 30000ms exceeded
[2025-05-26T05:31:00.568Z] [STDOUT] [31merror[39m: Error generating response with llama3:latest: {"service":"multi-agent-chat","timestamp":"2025-05-26T05:31:00.568Z"}
[2025-05-26T05:31:00.570Z] [STDOUT] [0mPOST /message [32m200[0m 90017.289 ms - 286[0m
[2025-05-26T05:32:55.594Z] [STDOUT] [32minfo[39m: Shutting down LLaMA 3 agent... {"service":"multi-agent-chat","timestamp":"2025-05-26T05:32:55.592Z"}
[2025-05-26T05:32:55.601Z] Process exited with code null
[2025-05-26T15:20:57.147Z] [STDOUT] [32minfo[39m: agent-llama3 running on port 3002 {"service":"multi-agent-chat","timestamp":"2025-05-26T15:20:57.145Z"}
[2025-05-26T15:21:04.676Z] [STDOUT] [0mGET /status [32m200[0m 1.313 ms - 66[0m
[2025-05-26T15:22:03.177Z] [STDOUT] [32minfo[39m: agent-llama3 received message {"from":"manager","service":"multi-agent-chat","timestamp":"2025-05-26T15:22:03.176Z"}
[2025-05-26T15:22:03.177Z] [STDOUT] Generating response with model: llama3:latest
[2025-05-26T15:22:19.214Z] [STDOUT] [0mPOST /message [32m200[0m 16036.550 ms - 3083[0m
[2025-05-26T15:23:14.538Z] [STDOUT] [32minfo[39m: agent-llama3 received message {"from":"manager","service":"multi-agent-chat","timestamp":"2025-05-26T15:23:14.537Z"}
[2025-05-26T15:23:14.538Z] [STDOUT] Generating response with model: llama3:latest
[2025-05-26T15:23:31.553Z] [STDOUT] [0mPOST /message [32m200[0m 17014.928 ms - 3109[0m
[2025-05-26T15:24:20.394Z] [STDOUT] [32minfo[39m: agent-llama3 received message {"from":"manager","service":"multi-agent-chat","timestamp":"2025-05-26T15:24:20.393Z"}
[2025-05-26T15:24:20.394Z] [STDOUT] Generating response with model: llama3:latest
[2025-05-26T15:24:30.252Z] [STDOUT] [0mPOST /message [32m200[0m 9858.163 ms - 1412[0m
[2025-05-26T15:30:04.986Z] [STDOUT] [32minfo[39m: Shutting down LLaMA 3 agent... {"service":"multi-agent-chat","timestamp":"2025-05-26T15:30:04.985Z"}
[2025-05-26T15:30:04.997Z] Process exited with code null
